
#
# This source file is part of appleseed.
# Visit http://appleseedhq.net/ for additional information and resources.
#
# This software is released under the MIT license.
#
# Copyright (c) 2013 Franz Beaune, Joel Daniels, Esteban Tovagliari.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

import os

class project_file_writer( object):
    def write( self, filename, scene):
        assert os.path.isabs( filename)

        if scene is None:
            # TODO: throw something here...
            return

        base_dir = os.path.split( filename)[0]
        os.makedirs( base_dir , exist_ok = True)

        self._geom_dir = os.path.join( base_dir, "geom")
        os.makedirs( self._geom_dir , exist_ok = True)

        self._texture_dir = os.path.join( base_dir, "tex")
        os.makedirs( self._texture_dir , exist_ok = True)

        with open( filename, "w") as self._output_file:
            self._indent = 0
            self.__emit_file_header()
            # ...

    def __emit_file_header( self):
        self.__emit_line( "<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
        self.__emit_line( "<!-- File generated by blender's render_appleseed. -->")

    #----------------------------------------------------------------------------------------------
    # Utilities.
    #----------------------------------------------------------------------------------------------

    def __open_element( self, name):
        self.__emit_line( "<" + name + ">")
        self.__indent()

    def __close_element( self, name):
        self.__unindent()
        self.__emit_line( "</" + name + ">")

    def __emit_line( self, line):
        self.__emit_indent()
        self._output_file.write( line + "\n")

    def __indent( self):
        self._indent += 1

    def __unindent( self):
        assert self._indent > 0
        self._indent -= 1

    def __emit_indent(self):
        self._output_file.write( " " * self._indent * 4)
