#
# This source file is part of appleseed.
# Visit http://appleseedhq.net/ for additional information and resources.
#
# This software is released under the MIT license.
#
# Copyright (c) 2012 Esteban Tovagliari.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

import bpy

class AppleseedProjectWriter( object):
    def __init__( self, out_file, scene):
        self.__indentation = 0
        self.__output_file = out_file
        self.__scene = scene

    def write( self):
        self.__emit_file_header()
        self.__emit_project()

    def __indent( self):
        self.__indentation += 1

    def __unindent( self):
        assert self.__indentation > 0
        self.__indentation -= 1

    def __emit_indent( self):
        IndentSize = 4
        self.__output_file.write( " " * self.__indentation * IndentSize)

    def __open_element( self, name):
        self.__emit_line( "<" + name + ">")
        self.__indent()

    def __close_element( self, name):
        self.__unindent()
        self.__emit_line( "</" + name + ">")

    def __emit_line( self, line):
        self.__emit_indent()
        self.__output_file.write( line + "\n")

    def __emit_file_header( self):
        self.__emit_line( "<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
        self.__emit_line( "<!-- File generated by render_appleseed. -->")

    def __emit_project( self):
        self.__open_element( "project")
        self.__close_element( "project")
